TOURCMS-8369 created functions add_header and set_request_identifier …
TourCMS/tourcms-php pull request #61
Opened 2023-05-17 15:36 UTC by palisis-frmar

…and changed the code to adapt to this change where now  is a property of the class

2023-05-17 15:44 UTC, palisis-juanra approved these changes

2023-05-17 15:44 UTC, palisis-juanra commented on src/TourCMS.php
> +		return $this->add_header('x-request-identifier', $value);
Looks good.
I would change it as `X-Request-Identifier` I think it is a most accurate standard naming for headers

2023-05-17 15:45 UTC, palisis-juanra requested changes
Looks good.
I would change it as X-Request-Identifier I think it is a most accurate standard naming for headers and also to be consistent with readme.md

2023-05-18 12:54 UTC, paulslugocki requested changes

2023-05-18 12:54 UTC, paulslugocki commented on src/TourCMS.php
> +		$value = $value . " (" . uniqid() . ")";
I'm not sure we should prepend our own unique id, we should let the implementer define that.

```suggestion
```

2023-05-18 13:24 UTC, paulslugocki approved these changes

2023-05-18 13:24 UTC, merged